openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

# By providing "/api" as the value of url, you’ll be able to access all of your API paths relative to http://localhost:8000/api.
servers:
  - url: "/api"

# define your API endpoints in a paths block:
paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
